### ISSUE TITLE
[Coleridge Initiative] EDA

### ISSUE THREAD

**Issue by heehehe** [heehehe/kaggle#3]
- [ ] 데이터 구조 파악
- [ ] EDA notebook 따라해보기 (예시 3-5개)
   - https://www.kaggle.com/pashupatigupta/starter-competition-data-eda-and-modelling
- [ ] notebook 올려보기
- [ ] 예측 모델 방향 잡기
